actstream/runtests/urls.py
import os

import django
from django.contrib import admin
from django.views.static import serve
try:
    from django.conf.urls import patterns, include, url
except ImportError:
    from django.conf.urls.defaults import patterns, include, url

admin.autodiscover()


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(?P<path>.*)$', serve,
        {'document_root': os.path.join(os.path.dirname(__file__), 'media')}),
    url(r'auth/', include('django.contrib.auth.urls')),
    url(r'testapp/', include('testapp.urls')),
    url(r'', include('actstream.urls')),
]

if django.VERSION[:2] < (1, 9):
    urlpatterns = patterns('', *urlpatterns)

actstream/urls.py
import django
try:
    from django.conf.urls import url
except ImportError:
    from django.conf.urls.defaults import url, patterns

from actstream import feeds, views


urlpatterns = [
    # User feeds
    url(r'^feed/$', feeds.UserActivityFeed(), name='actstream_feed'),
    url(r'^feed/atom/$', feeds.AtomUserActivityFeed(),
        name='actstream_feed_atom'),
    url(r'^feed/json/$', feeds.UserJSONActivityFeed.as_view(),
        name='actstream_feed_json'),

    # Model feeds
    url(r'^feed/(?P<content_type_id>[^/]+)/$',
        feeds.ModelActivityFeed(), name='actstream_model_feed'),
    url(r'^feed/(?P<content_type_id>[^/]+)/atom/$',
        feeds.AtomModelActivityFeed(), name='actstream_model_feed_atom'),
    url(r'^feed/(?P<content_type_id>[^/]+)/json/$',
        feeds.ModelJSONActivityFeed.as_view(), name='actstream_model_feed_json'),

    # Object feeds
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        feeds.ObjectActivityFeed(), name='actstream_object_feed'),
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/atom/$',
        feeds.AtomObjectActivityFeed(), name='actstream_object_feed_atom'),
    url(r'^feed/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/json/$',
        feeds.ObjectJSONActivityFeed.as_view(), name='actstream_object_feed_json'),

    # Follow/Unfollow API
    url(r'^follow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, name='actstream_follow'),
    url(r'^follow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'actor_only': False}, name='actstream_follow_all'),
    url(r'^unfollow_all/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'actor_only': False, 'do_follow': False}, name='actstream_unfollow_all'),
    url(r'^unfollow/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.follow_unfollow, {'do_follow': False}, name='actstream_unfollow'),

    # Follower and Actor lists
    url(r'^followers/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.followers, name='actstream_followers'),
    url(r'^following/(?P<user_id>[^/]+)/$',
        views.following, name='actstream_following'),
    url(r'^actors/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$',
        views.actor, name='actstream_actor'),
    url(r'^actors/(?P<content_type_id>[^/]+)/$',
        views.model, name='actstream_model'),

    url(r'^detail/(?P<action_id>[^/]+)/$', views.detail, name='actstream_detail'),
    url(r'^(?P<username>[^/]+)/$', views.user, name='actstream_user'),
    url(r'^$', views.stream, name='actstream'),
]

if django.VERSION[:2] < (1, 9):
    urlpatterns = patterns('', *urlpatterns)

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
# from django.conf.urls.i18n import i18n_patterns # not used right now
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required

from register.views import password_change
from socialee import views
from . import allauth_urls

from socialee.decorators import user_is_project_manager, user_is_profile_owner, user_is_request_user

urlpatterns = [
    
    url(r'^', include('landingpage.urls')), # ID 000

    url(r'^accounts/password/change/$', login_required(password_change), name='password_change'),
    url(r'^accounts/', include('allauth.urls')), # IDs 081, 082, 083, etc
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)), # ID 900
    url(r'^blog/', include('zinnia.urls')), # IDs 050, 051, 052, etc
    url(r'^comments/', include('django_comments.urls')), # für Blog
    url(r'^feedback/', include("feedback.urls")), # Feedback-App
    url(r'^ideen/', include('ideas.urls')), # TODO IDs vergeben
    url(r'^impressum/$', views.Impressum.as_view(), name='impressum'), # ID 021
    url(r'^registrieren/', include('register.urls'), name='register'), # ID 080
    url(r'^protect/', include('simple_auth.urls')), # password-protection for staging-server
    url(r'^question/', include('questions.urls')), # inaktiv, future feature
    url(r'^summernote/', include('django_summernote.urls')), # für Blog
    url(r'^styleguide/$', views.Styleguide.as_view(), name='styleguide'),
    url(r'^zitat/', include('quotes.urls')), # ID 024

    # LOGIN REQUIRED
    url(r'^startproject/$', login_required(views.StartProject.as_view()), name='startproject'), # ID 100
    url(r'^startproject/(?P<idea>\w+)$', login_required(views.StartProject.as_view()), name='startprojectWithIdea'), 
    url(r'^project_overview/$', views.ProjectOverview.as_view(), name='project_overview'), # ID 101
    url(r'^project/(?P<slug>[-\w]+)/$', login_required(views.ProjectView.as_view()), name='project_view'), # ID 102
    url(r'^project/(?P<slug>[-\w]+)/edit/$', login_required(user_is_project_manager(views.ProjectUpdateView.as_view())), name='project_updateview'), # ID 103
    
    url(r'^startprofile/$', login_required(views.StartProfile.as_view()), name='startprofile'),
    url(r'^profile/(?P<slug>[\w.@+-]+)/willkommen/$', login_required(user_is_request_user(views.WelcomePage.as_view())), name='welcome'), # ID 200
    url(r'^profile/(?P<slug>[\w.@+-]+)/$', login_required(views.ProfileView.as_view()), name='profile_view'), # ID 203
    url(r'^profile/(?P<slug>[\w.@+-]+)/edit/$', login_required(user_is_profile_owner(views.ProfileUpdateView.as_view())), name='profile_updateview'), # ID 201

    url(r'^user/(?P<slug>[\w.@+-]+)/edit/$', login_required(user_is_request_user(views.UserUpdateView.as_view())), name='user_updateview'), # ID 201

    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    url(r'^activity/', include('actstream.urls')),

    #face view for user interagtion
    #url(r'^profile/(?P<slug>[\w.@+-]+)/socialeebhaber/$', login_required(views.Socialeebhaber.as_view()), name='socialeebhaber'),
    url(r'^comment/$', login_required(views.Comment.as_view()), name='comment'),
    url(r'^follow/$', login_required(views.Follow.as_view()), name='comment'),
    url(r'^actAs/$', login_required(views.ActAs.as_view()), name='actAs'),
    url(r'^like/$', login_required(views.Like.as_view()), name='like_message'),
]

if not settings.PROD:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ideas/urls.py
from django.conf.urls import url
from .decorators import is_idea_not_private, user_is_idea_author

from . import views

urlpatterns = [
    url(r'^$', views.IdeaListView.as_view(), name='idea_list'),
    url(r'^neu/$', views.CreateIdea.as_view(), name='create_idea'),
    url(r'^idea_like/$', views.Like.as_view(), name='idea_like'),
    url(r'^idea_comment/$', views.Commentate.as_view(), name='idea_comment'),
    url(r'^(?P<pk>\d+)$', is_idea_not_private(views.IdeaDetailView.as_view()), name='idea_detail'),
    url(r'^edit/(?P<pk>\d+)$', user_is_idea_author(views.IdeaEditView.as_view()), name='idea_edit'),
    url(r'^delete/(?P<pk>\d+)$', user_is_idea_author(views.IdeaDeleteView.as_view()), name='delete_idea'),

    url(r'^neu/(?P<message>\w+)$', views.CreateIdea.as_view(), name='create_idea_with_message'),
]

ideas/models.py
import datetime

from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.models import User, Group
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User


def upload_location(instance, filename):
    title = str(instance.title)
    now = datetime.datetime.now()
    date = now.strftime("%Y-%m-%d_%HUhr%M")
    return "%s/%s/%s/%s" % (str("ideas"), title, date, filename)


class Idea(models.Model):
    picture = models.ImageField(upload_to=upload_location, null=True, blank=True, verbose_name='Bild')
    title = models.CharField(max_length=250, verbose_name='Titel', null=True, blank=True)
    description = models.TextField(max_length=1500, verbose_name='Beschreibung', null=True, blank=True)
    author = models.EmailField(max_length=254, verbose_name='Email des Autors', null=True, blank=True)
    authorUser = models.ForeignKey(User, null=True, blank=True)
    subm_date = models.DateTimeField(auto_now_add=True, verbose_name='Datum', null=True, blank=True)
    featured = models.BooleanField(default=False, verbose_name='featured')
    private = models.BooleanField(default=False, verbose_name='Privat ')
    enabled = models.BooleanField(default=False, verbose_name='Freigegeben')
    active = models.BooleanField(default=True, verbose_name='Ohne Projekt')
    likes = models.ManyToManyField(User, related_name='likes_ideas')
    project = models.OneToOneField('socialee.Project', null=True, blank=True)

    class Meta:
        verbose_name = 'Idee'
        verbose_name_plural = 'Ideen'


    def was_submitted_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(hours=24) <= self.subm_date <= now
    was_submitted_recently.admin_order_field = 'subm_date'
    was_submitted_recently.boolean = True
    was_submitted_recently.short_description = 'Neu'


    def thumb(self):
        if self.picture:
            return mark_safe(u'<img src="%s" width=60 height=60 />' % (self.picture.url))
        else:
            return u''

    thumb.short_description = 'Vorschau'

    # def has_delete_permission(self, request, obj=None):
    #     if obj and obj.private and hasattr(request.user, 'email') and request.user.email != obj.author:
    #         print("inhere")
    #         return False
    #     print("nope")
    #     return super(Idea, self).has_delete_permission(request, obj)

    def __str__(self):
        return format(self.title)

    def get_absolute_url(self):
        return reverse('idea_detail', kwargs = {"pk": self.pk})

class Comment(models.Model):
    to_idea = models.ForeignKey(Idea, null=True, blank=True, related_name='comments')
    by_user = models.ForeignKey(User, null=True, blank=True)
    message = models.TextField(max_length=140, null=True, blank=True)
    date = models.DateTimeField(auto_now=False, auto_now_add=True)
    class Meta:
        ordering = ['-date']

ideas/forms.py
from django import forms
from collections import OrderedDict
from register.forms import *
from django.forms import *

from .models import Idea

from django.utils.translation import ugettext_lazy as _ 


class IdeaForm(EmailRegisterForm):

    picture = ImageField( required=False, widget = FileInput( attrs={'class' : 'input_with_img'} ) )
    picturefile = CharField( #Add room throws DoesNotExist error
                            widget=HiddenInput,       
                            required=False,
                            label='')
    title = CharField( required=False, widget = TextInput( attrs={ 'autofocus': 'autofocus' }))
    description = CharField( required=False, widget=Textarea(attrs={'cols': 80, 'rows': 5, 'max_length':1500, 'class':'input_with_bound'}))
    YESNO_CHOICES = ((1, 'Ja'),(0, 'Nein')) 
    private = ChoiceField(
                     choices=YESNO_CHOICES, widget=RadioSelect
                )

    def __init__(self, *args, **kwargs):
        super(IdeaForm, self).__init__(*args, **kwargs)
        fields_key_order = ['picture', 'picturefile', 'title', 'description', 'private', 'email']
        self.fields = OrderedDict((k, self.fields[k]) for k in fields_key_order)

        self.fields['email'].required = False
        self.fields['picture'].label = _('')
        self.fields['title'].label = _('Ideen-Titel')
        self.fields['description'].label = _('Beschreibung der Idee')
        self.fields['private'].label = _('Möchtest du, dass nur du diese Idee sehen kannst? Du kannst das später jederzeit ändern.')
        self.fields['private'].initial = 0

        self.fields['picture'].help_text = _('')
        self.fields['title'].help_text = _('')
        self.fields['description'].help_text = _('')

    def custom_signup(self, request, user):
        request.session["idea_register"] = True
        return super(IdeaForm, self).custom_signup(request, user)


class IdeaEditForm(ModelForm):

    class Meta:
        model = Idea
        fields = ('picture', 'title', 'description', 'private')
        labels = {
            'picture' : _('Idee als Bild'),
            'title': _('Ideen-Titel'),
            'description' : _('Beschreibung der Idee'),
            'private' :  _(' Private Idee? '),
        }
        widgets = {
            'picture' : ClearableFileInput( attrs={'class' : 'input_with_img'} ),
            'title': TextInput( attrs={ 'autofocus': 'autofocus' }),
            'description' : Textarea(attrs={'cols': 80, 'rows': 5, 'max_length':1500, 'class':'input_with_bound'}),
        }

ideas/templates/create_idea.html
{% extends "offcanvas.html" %}
{% load static sekizai_tags %}

{% block content %}

<div class="bg-img">
  <div class="row align-center">
    <div class="small-12 medium-10 large-8 columns">
      <div class="c-form">

        <h3 id="top_titel">Was ist deine Idee?</h3>
        <p id="top_desc">Egal, ob groß oder klein. Mit einer Idee fängt es immer an.</p>

        <form method="POST" id="form_id" enctype="multipart/form-data">{% csrf_token %}

          <div id="idea_form">
            <div class="row">
              {% include "snippet_formfield.html" with field=form.picture size="small-12" upload_val="Bild hochladen" %}
              {% include "snippet_formfield.html" with field=form.title size="small-12" %}
              {% include "snippet_formfield.html" with field=form.description size="small-12" len_restricted="true" %}
              {% include "snippet_formfield.html" with field=form.private size="small-12" %}
            </div>
            <div class="c-form__footer">
              <div id="review_button" class="button">Vorschau deiner Idee</div>
              <a href="{% url 'idea_list' %}" class="text-link-special pull-right">zurück zur Übersicht</a>
            </div>
          </div>

          <div id="review">
            
            <div class="row">
              <div class="small-12 medium-4 columns">
                {% include "idea_card.html" with idea="preview" %}
              </div>
            </div>

            {% if not request.user.is_authenticated %}
            <div class="row">
              <div class="small-12 columns">
                <p>Trage noch deine E-Mail-Adresse ein und erstelle dir ein Konto bei Socialee.</p>  
              </div>
              {% include "snippet_formfield.html" with field=form.email size="small-12" %}  
            </div> 
            {% endif %}

            <div class="c-form__footer">
              <input class="button" type="submit" value="Idee Absenden" />
              <a id="change" class="text-link-special pull-right float-right">Idee nochmal ändern</a>
            </div>

          </div>

        </form>
        
      </div>
    </div>
  </div>
</div>

{% addtoblock 'js' %}
<script type="text/javascript">


function fixPreview()
{
  $("#idea_title").html($("#id_title").val());
  $("#idea_description").html($("#id_description").val());
  $("#idea_img").attr("src", $("#id_picture").parents("fieldset").first().find("img").attr("src"));
}


{% if reload %}
$("#idea_form").children().hide();
$("#idea_title").html($("#id_title").val());
$("#idea_description").html($("#id_description").val());
$("#top_desc").html("Falls du ein Bild hattest, das musst du nochmal hochladen...");
{% else %}
$("#review").hide();
$("#id_email").parent().hide();
{% endif %}

$("#review_button").click(function()
  {
    if($("#id_title").val() || $("#id_description").val() || $("#id_picture").val())
    {
      fixPreview();
      $("#idea_form").children().hide();
      $("#review").show();
      $("#id_email").parent().show();
      
      $("#top_desc").html("");
      $("#top_titel").html("Sieht gut aus, oder?!");
    }
    else
    {
      $("#top_desc").html("Eines der Felder musst du aber schon ausfüllen ;-) Oder einfach nur ein Bild hochladen.").css("color", "red");
    }

  });

$("#change").click(function()
  {
    $("#review").hide();
    $("#id_email").parent().hide();
    $("#idea_form").children().show();

    $("#top_desc").html("Mach sie noch hübscher!").css("color", "black");
    $("#top_titel").html("Gute Idee!");
  });

</script>
{% endaddtoblock %}

{% endblock content %}

ideas/templates/edit_idea.html
{% extends "offcanvas.html" %}
{% load static sekizai_tags %}

{% block content %}

  <div class="row align-center">
    <div class="medium-10 large-8 columns">
      <div class="c-form">

        <h3>Idee bearbeiten</h3>

        <a class="button hollow" href="{% url 'delete_idea' object.id %}"><i class="fa fa-close" aria-hidden="true"></i> Idee löschen</a>

        <form method="POST" id="form_id" enctype="multipart/form-data">{% csrf_token %}

          <div id="idea_form">
            <div class="row">
              {% include "snippet_formfield.html" with field=form.picture size="small-12" upload_val=" Bild hochladen " %}
              {% include "snippet_formfield.html" with field=form.title size="small-12" %}
              {% include "snippet_formfield.html" with field=form.description size="small-12" len_restricted="true" %}
              {% include "snippet_formfield.html" with field=form.private size="small-12" %}
            </div>
            
            <input class="button" type="submit" value="Speichern" />
          </div>
        </form>
        
      </div>
    </div>
  </div>

{% addtoblock 'js' %}
<script type="text/javascript">

{% if object.picture %}
$(".input_with_img").parents("fieldset").first().find("img").attr("src", "{{ MEDIA_URL }}{{ object.picture }}");
{% endif %}

</script>
{% endaddtoblock %}
{% endblock content %}

ideas/templates/idea_card.html
{% load socialee_filters static %}

{# Edit-Mode if own idea #}
{% if request.user.email == idea.author %}
<div class="card edit">
{% else %}
<div class="card">
{% endif %}

  <div class="card-section">
    <a {% if idea != "preview" %} href="{% url 'idea_detail' idea.pk %}" {% endif %}>
    {# Bild und Label #}
    {% if idea.picture or idea == "preview" %}
      <img class="float-center" src="{{ MEDIA_URL }}{{ idea.picture }}" id="idea_img">
      <div class="row align-center">
      {% if idea.active %}
        <div class="socialee-label shrink column text-center">Idee</div>
      {% else %}
        <div class="socialee-label grey shrink column text-center">Idee</div>
      {% endif %}
      </div>
    {% else %}
      <div class="row align-center">
        <div class="socialee-label shrink column text-center">Idee</div>
      </div>
    {% endif %}
    {# End Bild und Label #}

    {# Statusbereich #}
    {% if idea.private or not idea.active or not idea.enabled %}
    <div class="row align-center text-center mt-05rem">
      
      {% if not idea.active and idea != "preview"%}
      <div class="columns">
        <p class="meta mb-0">Inzwischen ein Projekt</p>
      </div>
      {% endif %}

      {% if not idea.enabled %}
      <div class="columns">
        <p class="meta mb-0">wird geprüft</p>
      </div>
      {% endif %}

      {% if idea.private %}
      <div class="columns">
        <p class="meta red mb-0"><i class="fa fa-lock" aria-hidden="true"></i><strong> Nicht öffentlich</strong></p>
      </div>  
      {% endif %}
    </div>

    <div class="separator-line"></div>
    {% endif %}
    {# END Statusbereich #}


    {# Titel #}
    <h4 class="text-center mt-05rem" id="idea_title">{{ idea.title }}</h4>

    {# Beschreibung #}
    <p class="text-center small" id="idea_description">{{ idea.description|truncatechars:600|urlizetrunc:25|url_target_blank|safe }}{% if idea.description|length > 599 %} |<a href="{% url 'idea_detail' idea.pk %}"> mehr</a>{% endif %}</p>

    {# Link zur Projektseite #}
    {% if not idea.active and idea != "preview" %}
    <div class="row align-center">
      <a class="button darkblue small" href="{% url 'project_view' idea.project.slug %}">Projektseite öffnen</a>
    </div>
    {% endif %}

    {# Autor & Zeit #} 
    <p class="meta text-center mt-2rem mb-0">{% if idea.authorUser %}{{ idea.authorUser }} {% else %} Anonym {% endif %} &#183; vor {{ idea.subm_date|timesince}}</p>
    <div class="separator-line"></div>

    </a>

    {# Likes und Kommentare #} {# get like-counts up and running #}
    <div class="row align-center">
      <div class="small-4 column">
      
        {% if request.user.is_authenticated %}

            {% if idea in request.user.likes_ideas.all  %}
            <div class="button-wrapper" idea_id="{{ idea.id }}" id="heart_{{ idea.id }}">
              <div class="like-button orange">
                <i class="fa fa-heart orange" aria-hidden="true"> {{ idea.likes.count }}</i>
              </div>
            </div>
            {% else %}
            <div class="button-wrapper" idea_id="{{ idea.id }}" id="heart_{{ idea.id }}">
              <div class="like-button grey">
                <i class="fa fa-heart" aria-hidden="true"> {{ idea.likes.count }}</i>
              </div>
            </div>
            {% endif %}
          
        {% else %}

          <div class="button-wrapper">
            <div class="like-button grey">
              <a href="{% url 'account_login' %}"><i class="fa fa-heart" aria-hidden="true"> {{ idea.likes.count }}</i></a>
            </div>
          </div>

        {% endif %}

      </div>

      <div class="small-4 column">
        <div class="button-wrapper">
          <div class="button-pill">
            <i class="fa fa-comment" aria-hidden="true"> {{ idea.comments.count }}</i>
          </div>
        </div>
      </div>

    </div>    

  </div>
  {% if request.user.email == idea.author %}
  <div class="row">
    <div class="small-12 columns card-edit-section">
      <p class="text-center mb-0"><a href="{% url 'idea_edit' idea.pk %}"><i class="fa fa-pencil"></i> Idee bearbeiten</a></p>
    </div>
  </div>
  {% endif %}
</div>

ideas/templates/idea_confirm_delete.html
{% extends "offcanvas.html" %}
{% load static %}

{% block content %}
<div class="bg-img">
  <div class="row align-center">
    <div class="small-12 medium-10 large-8 columns">
      <div class="c-form">
        <form action="" method="post">{% csrf_token %}
            <div class="row">
              <div>Willst du deine Idee "{{ object }}" wirklich löschen?</div>
            </div>
            <div class="c-form__footer">
              <input class="button" type="submit" value='Ja weg damit' />
              <a href="{% url 'idea_list' %}" class="text-link-special pull-right">zurück zur Übersicht</a>
            </div>
            
            
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

ideas/templates/idea_detail.html
{% extends "offcanvas.html" %}
{% load static sekizai_tags idea_tags socialee_filters %}

{% block content %}

<div class="row align-center">
  <div class="small-11 medium-10 large-10 columns">
    <div class="c-box">

      <div class="row align-center">
        <div class="small-12 medium-10 large-10 columns">
          
          <h2 class="text-center mb-2rem">{{ idea.title }}</h2>
          {% if idea.picture %}
          <img class="float-center" src="{{ MEDIA_URL }}{{ idea.picture }}">
            <div class="row align-center">
              <div class="socialee-label shrink column text-center">Idee</div>
            </div>
          {% endif %}
          {% if not idea.active %}
          <div class="row align-center">
            <div class="small-12 columns text-center">
              Diese Idee ist schon zum Projekt geworden. <br><a class="button hollow" href="{% url 'project_view' idea.project.slug %}">zum Projekt</a>
            </div>
          </div>
          {% elif idea.authorUser == request.user %}
          <div class="row align-center">
            <div class="small-12 columns text-center">
              <a class="button hollow" href="{% url 'idea_edit' idea.pk %}"><i class="fa fa-pencil" aria-hidden="true"></i>Idee bearbeiten</a>
            </div>
          </div>
          {% endif %}
          <p class="text-center mt-2rem">{{ idea.description|urlizetrunc:25|url_target_blank|safe }}</p>

          <div class="black-c-box small">

            {% if request.user.is_authenticated and idea.active %}
              <h5 class="idea-comments__title">Diskutiere mit bei {{ idea.title }}</h5>
              <div class="idea-comments__input">

                  <textarea autofocus="autofocus" class="input_with_bound" id="idea_comment_{{idea.id}}" name="idea_comment" rows="2" max_length="140"></textarea> 
                  <label for="idea_comment_{{idea.id}}" class="idea-comments__label float-right">140 Zeichen übrig</label>
                  <a class="button button--yellow button--icon idea_comment_button" id="idea_comment_button_{{ idea.id }}" idea_id="{{ idea.id }}">Kommentieren</a>
              </div>    
            {% elif idea.active %}
              <p class="white text-center">Dazu fällt dir was ein?<br><a class="button hollow" href="{% url 'register' %}?next={{ request.path }}">Jetzt registrieren</a><br><a class="text-link-special" href="{% url 'account_login' %}?next={{ request.path }}">oder anmelden.</a></p>
            {% endif %}

            <div id="idea_comments_{{idea.id}}">
              {% for comment in idea.comments.all %}
                {% include 'snippet_ideas_comment.html' %}
              {% endfor %}
            </div>

          </div>

          {% if request.user.is_authenticated and idea.active and idea.enabled %}
            {% if request.user.is_superuser %} {# or request.user.email == idea.author #}
            
              <div class="row align-center">
                <div class="small-12 columns text-center">
                  <br><a class="button hollow" href="{% url 'startprojectWithIdea' idea.pk %}">zum Projekt machen</a>
                </div>
              </div>

            {% endif %}
          {% endif %}
          

        </div>
      </div>
    </div>
  </div>  
</div>


{% addtoblock 'js' %}
<script type="text/javascript">
function idea_comment(idea_id, comment) {
    post_to_url( '{% url "idea_comment" %}',
                { idea_id : idea_id,
                  comment: comment
                },
                function(data){

                  var new_comment = $(data);
                  new_comment.hide();
                  $("#idea_comments_"+idea_id).prepend(new_comment);
                  $(new_comment).slideDown();
                });
  }

$(".idea_comment_button").click(
  function()
  {
    var id = $(this).attr('idea_id');
    if(  $.trim( $("#idea_comment_"+id).val()) )
      idea_comment(id, $("#idea_comment_"+id).val());
    $("#idea_comment_"+id).val("");
  });

</script>
{% endaddtoblock %}

{% endblock content %}